monster_data = {
    'squid': {'id': 1,
              'health': 1,
              'exp': 10,
              'attack': 50,
              'attack_type': 'slash',
              'speed': 3,
              'knockback': 20,
              'attack_radius': 80,
              'notice_radius': 360},

    'raccoon': {'id': 2,
                'health': 1,
                'exp': 25,
                'attack': 80,
                'attack_type': 'claw',
                'speed': 2,
                'knockback': 10,
                'attack_radius': 120,
                'notice_radius': 400},

    'spirit': {'id': 3,
               'health': 1,
               'exp': 11,
               'attack': 60,
               'attack_type': 'thunder',
               'speed': 4,
               'knockback': 20,
               'attack_radius': 60,
               'notice_radius': 350},

    'bamboo': {'id': 4,
               'health': 1,
               'exp': 9,
               'attack': 20,
               'attack_type': 'leaf_attack',
               'speed': 3,
               'knockback': 20,
               'attack_radius': 50,
               'notice_radius': 300}
}
