monster_data = {
    'squid': {'id': 1,
              'health': 1,
              'exp': 10,
              'attack': 2,
              'attack_type': 'slash',
              'speed': 3,
              'knockback': 20,
              'attack_radius': 100,
              'notice_radius': 200},

    'raccoon': {'id': 2,
                'health': 1,
                'exp': 25,
                'attack':5,
                'attack_type': 'claw',
                'speed': 2,
                'knockback': 10,
                'attack_radius': 100,
                'notice_radius': 180},

    'spirit': {'id': 3,
               'health': 1,
               'exp': 11,
               'attack': 2,
               'attack_type': 'thunder',
               'speed': 4,
               'knockback': 20,
               'attack_radius': 100,
               'notice_radius': 220},

    'bamboo': {'id': 4,
               'health': 1,
               'exp': 9,
               'attack': 1,
               'attack_type': 'leaf_attack',
               'speed': 3,
               'knockback': 20,
               'attack_radius': 100,
               'notice_radius': 300}
}
